In [1]:
conda list

# packages in environment at C:\Users\user\anaconda3:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0                    py38_0  
alabaster                 0.7.12                     py_0  
anaconda                  2020.11                  py38_0  
anaconda-client           1.7.2                    py38_0  
anaconda-navigator        1.10.0                   py38_0  
anaconda-project          0.8.4                      py_0  
argh                      0.26.2                   py38_0  
argon2-cffi               20.1.0           py38he774522_1  
asn1crypto                1.4.0                      py_0  
astroid                   2.4.2                    py38_0  
astropy                   4.0.2            py38he774522_0  
async_generator           1.10                       py_0  
atomicwrites              1.4.0                      py_0  
attrs                     20.3.0             pyhd3eb1b0_0  
autopep8                  1.5.4      

In [2]:
import numpy as np

In [3]:
ar= np.array([0,1,2,3,4,5,6,7,8,9])
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
type(ar)

numpy.ndarray

In [5]:
x= np.array([0,12,22,345,456,89,789])
x

array([  0,  12,  22, 345, 456,  89, 789])

In [6]:
2*x

array([   0,   24,   44,  690,  912,  178, 1578])

In [7]:
c=np.array([[0,1,2],[3,4,5]])
c

array([[0, 1, 2],
       [3, 4, 5]])

In [8]:
len(c)

2

In [9]:
len(c[0])

3

In [10]:
a=np.array([[10,20,30,40],[50,60,70,80]])
a

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [12]:
import pandas as pd

In [13]:
pd.DataFrame(a)

0   1   2   3
0  10  20  30  40
1  50  60  70  80

In [16]:
len(a)


2

In [17]:
len(a[0])

4

In [19]:
d=np.array([[[1,2,3,4,5],[4,5,6,8,4],[8,5,6,8,4],[8,4,6,8,5]],[[7,5,8,4,6],[8,5,2,4,8],[4,5,6,2,8],[8,6,8,4,8]],[[1,2,1,2,1],[1,2,1,2,1],[5,1,22,1,2],[1,1,1,1,1]]])
d

array([[[ 1,  2,  3,  4,  5],
        [ 4,  5,  6,  8,  4],
        [ 8,  5,  6,  8,  4],
        [ 8,  4,  6,  8,  5]],

       [[ 7,  5,  8,  4,  6],
        [ 8,  5,  2,  4,  8],
        [ 4,  5,  6,  2,  8],
        [ 8,  6,  8,  4,  8]],

       [[ 1,  2,  1,  2,  1],
        [ 1,  2,  1,  2,  1],
        [ 5,  1, 22,  1,  2],
        [ 1,  1,  1,  1,  1]]])

In [20]:
len(d)

3

In [21]:
len(d[0])

4

In [23]:
len(d[0][0])

5

In [25]:
ar.ndim

1

In [26]:
ar.shape

(10,)

In [27]:
a.ndim

2

In [28]:
a.shape

(2, 4)

In [30]:
d.ndim

3

In [31]:
d.shape

(3, 4, 5)

In [33]:
d[2,2,2]

22

In [34]:
m = np.array([[ 0,  1,  2,  3,  4],
            [ 5,  6,  7,  8,  9],
            [10, 11, 12, 13, 14]])

In [35]:
m[1,2]

7

In [36]:
m[2,4]

14

In [38]:
m[1,1:3]

array([6, 7])

In [39]:
m[1:3,2]

array([ 7, 12])

In [40]:
m[0:2,3:5]

array([[3, 4],
       [8, 9]])

In [41]:
a= np.array([11,22,33,44,55,66,77,88,99])
idx=np.array([0,2,4,6,8])
a[idx]

array([11, 33, 55, 77, 99])

In [43]:
a = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
idx = np.array([0,8,0,8,0,8,0,8,0,8,0,8])
a[idx]

array([11, 99, 11, 99, 11, 99, 11, 99, 11, 99, 11, 99])

In [45]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,2,4,5]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 2, 4, 5]])

In [46]:
pd.DataFrame(a)

0  1  2  3
0  1  2  3  4
1  5  6  7  8
2  9  2  4  5

In [47]:
a[:,[True,False,False,True]]

array([[1, 4],
       [5, 8],
       [9, 5]])

In [48]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [49]:
x%3

array([1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2],
      dtype=int32)

In [50]:
x%3==0

array([False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False, False])

In [51]:
x[x%3==0]

array([ 3,  6,  9, 12, 15, 18])

In [52]:
x[x%4==1]

array([ 1,  5,  9, 13, 17])

In [58]:
x[(x%3==0)&(x%4==1)]

array([9])

In [61]:
b=np.array([1,2,3],dtype='U')
b.dtype

dtype('<U1')

In [62]:
b[0]+b[1]

'12'

In [64]:
e=np.ones((2,3,4),dtype="i")
e

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int32)

In [65]:
g=np.empty((4,3))
g

array([[1.24571008e-311, 3.16202013e-322, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 1.04896866e+165],
       [5.11108569e-038, 1.48609441e-076, 3.05699398e-057],
       [6.04972514e-066, 1.56260670e+185, 4.85499502e-033]])

In [68]:
k=np.array([[1,2,3],[4,5,6]])
k

array([[1, 2, 3],
       [4, 5, 6]])

In [69]:
k.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [71]:
o=np.arange(12)
o

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [72]:
w=o.reshape(3,4)

In [73]:
w

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [74]:
w=o.reshape(2,3,2)
w

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [76]:
w.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [78]:
a1=np.ones((2,3),dtype="i")
a1
a2=np.zeros((2,2),dtype="i")
a2
np.hstack([a1,a2])

array([[1, 1, 1, 0, 0],
       [1, 1, 1, 0, 0]], dtype=int32)

In [79]:
a3=np.ones((2,4),dtype="i")
np.hstack([a1,a2,a3])

array([[1, 1, 1, 0, 0, 1, 1, 1, 1],
       [1, 1, 1, 0, 0, 1, 1, 1, 1]], dtype=int32)

In [80]:
v1=np.ones((3,2),dtype="i")
v2=np.zeros((1,2),dtype="i")
v3=np.ones((4,2),dtype="i")
np.vstack([v1,v2,v3])

array([[1, 1],
       [1, 1],
       [1, 1],
       [0, 0],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]], dtype=int32)

❤💖💖💖💖💖💖💖12월 2일 넘파이 💖💖💖💖💖💖💖💖💖💖💖💖💖💖💖💖💖💖💖💖💖💖💖💖💖💖💖💖💖💖💖💖💖💖💖

In [3]:
import numpy as np

In [4]:
x=np.arange(3)
x

array([0, 1, 2])

In [5]:
y=np.arange(5)
y

array([0, 1, 2, 3, 4])

In [6]:
X,Y = np.meshgrid(x,y)

In [7]:
X

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [8]:
Y

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [9]:
[list(zip(x,y)) for x,y in zip(X,Y)]

[[(0, 0), (1, 0), (2, 0)],
 [(0, 1), (1, 1), (2, 1)],
 [(0, 2), (1, 2), (2, 2)],
 [(0, 3), (1, 3), (2, 3)],
 [(0, 4), (1, 4), (2, 4)]]

In [10]:
x=np.arange(1,10001)
y=np.arange(10001,20001)

z=np.zeros_like(x)
for i in range(10000):
    z[i]=x[i] +y[i]

In [11]:
z[:5]

array([10002, 10004, 10006, 10008, 10010])

In [13]:
a = np.array([1,2,3,4])
b = np.array([4,2,3,1])
a==b

array([False,  True,  True, False])

In [14]:
a>=b

array([False,  True,  True,  True])

In [16]:
a= np.array([1,2,3,4])
b=np.array([4,2,2,4])
c= np.array([1,2,3,4])

In [17]:
np.all( a==b)

False

In [18]:
np.all(a==c)

True

In [20]:
a=np.arange(5)
a

array([0, 1, 2, 3, 4])

In [21]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [22]:
10**a

array([    1,    10,   100,  1000, 10000], dtype=int32)

In [23]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
x*100


array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [26]:
x=np.arange(12).reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [27]:
100*x

array([[   0,  100,  200,  300],
       [ 400,  500,  600,  700],
       [ 800,  900, 1000, 1100]])

In [28]:
k=np.array([[1,2],[2,3]])
k

array([[1, 2],
       [2, 3]])

In [30]:
k=np.arange(1,101).reshape(4,5,5)
k

array([[[  1,   2,   3,   4,   5],
        [  6,   7,   8,   9,  10],
        [ 11,  12,  13,  14,  15],
        [ 16,  17,  18,  19,  20],
        [ 21,  22,  23,  24,  25]],

       [[ 26,  27,  28,  29,  30],
        [ 31,  32,  33,  34,  35],
        [ 36,  37,  38,  39,  40],
        [ 41,  42,  43,  44,  45],
        [ 46,  47,  48,  49,  50]],

       [[ 51,  52,  53,  54,  55],
        [ 56,  57,  58,  59,  60],
        [ 61,  62,  63,  64,  65],
        [ 66,  67,  68,  69,  70],
        [ 71,  72,  73,  74,  75]],

       [[ 76,  77,  78,  79,  80],
        [ 81,  82,  83,  84,  85],
        [ 86,  87,  88,  89,  90],
        [ 91,  92,  93,  94,  95],
        [ 96,  97,  98,  99, 100]]])

In [31]:
x = np.array([1, 2, 3, 4])
x

array([1, 2, 3, 4])

In [32]:
np.sum(x)

10

In [33]:
np.min(x)

1

In [34]:
np.max(x)

4

In [37]:
np.mean(x)

2.5

In [40]:
np.all([True,True,False])

False

In [41]:
a=np.zeros((100,100),dtype="i")
a

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int32)

In [42]:
import pandas as pd

In [43]:
pd.DataFrame(a)

0   1   2   3   4   5   6   7   8   9   ...  90  91  92  93  94  95  96  \
0    0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
1    0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
2    0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
3    0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
4    0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ..  ..  ..  ..  ..  ..  ..   
95   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
96   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
97   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
98   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
99   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   

    97  98  99  
0    0   0   0  
1    0   0   0  
2    0   0   0  
3    0   0   0  
4    0   0   0  
..  ..  ..  ..  
95   0   0   0  
96   0   0   0  
97   0   0   0  
98   0   0   0  
99   0   0   0  

[100 rows x 100 columns]

In [44]:
np.all(a==0)

True

In [46]:
x=np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [51]:
x.sum(axis=0)

array([4, 6])

In [50]:
x.sum(axis=1)

array([3, 7])

In [57]:
f=np.arange(30,dtype="i").reshape(5,6)
f

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]], dtype=int32)

In [58]:
f.sum()

435

In [59]:
f.sum(axis=1)

array([ 15,  51,  87, 123, 159], dtype=int32)

In [60]:
f.max(axis=1)

array([ 5, 11, 17, 23, 29], dtype=int32)

In [61]:
f.mean(axis=0)

array([12., 13., 14., 15., 16., 17.])

In [62]:
f.min(axis=0)

array([0, 1, 2, 3, 4, 5], dtype=int32)

In [63]:
a = np.array([[4,  3,  5,  7],
              [1, 12, 11,  9],
              [2, 15,  1, 14]])
a

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2, 15,  1, 14]])

In [67]:
z=np.sort(a,axis=1)
z

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [68]:
np.sort(z,axis=0)

array([[ 1,  2,  5,  7],
       [ 1,  4, 11, 12],
       [ 3,  9, 14, 15]])

In [72]:
a=np.array([[  1,    2,    3,    4],
       [ 46,   99,  100,   71],
       [ 81,   59,   90,  100]])


In [80]:
np.random.seed(9)

In [81]:
np.random.rand(5)

array([0.01037415, 0.50187459, 0.49577329, 0.13382953, 0.14211109])

In [83]:
np.random.choice(10,3,replace=False)

array([7, 2, 6])

In [87]:
j=np.random.randint(1,7,100)
j

array([6, 2, 5, 5, 4, 1, 4, 4, 4, 3, 1, 6, 3, 4, 6, 3, 3, 6, 6, 6, 5, 5,
       5, 2, 1, 1, 5, 6, 4, 1, 5, 4, 3, 1, 5, 3, 1, 2, 4, 3, 5, 2, 2, 2,
       5, 1, 6, 4, 4, 4, 4, 4, 5, 6, 2, 4, 2, 1, 2, 3, 4, 1, 2, 6, 1, 1,
       6, 5, 3, 1, 2, 2, 4, 4, 5, 5, 3, 4, 5, 1, 1, 6, 1, 6, 3, 5, 3, 2,
       5, 1, 6, 6, 3, 4, 4, 4, 1, 1, 2, 3])

In [88]:
np.mean(j)

3.48

In [90]:
d=np.random.randint(0,2,10)
d

array([1, 0, 1, 0, 0, 1, 1, 0, 1, 1])

In [97]:
g=np.random.randn(250)
g

array([-0.38949117,  0.42823929,  0.2922315 ,  1.48040975,  0.81850583,
       -0.11729247, -1.35270124, -2.09500777, -0.43953304, -0.07269961,
        0.06473725,  0.74104875,  1.04906257,  1.20140993, -1.04252588,
       -0.34589399, -0.67009834, -0.49984017,  0.88593755,  1.02482432,
        0.00713397, -0.56866505, -0.19422545,  0.92490856, -1.6464961 ,
        0.19179775,  0.32518845,  1.23276314, -1.25992453,  1.28852116,
       -1.04733977,  0.18540823, -0.22451131,  0.37457795, -0.23947733,
       -0.93277099,  0.46021078,  1.68765732, -0.72767246,  0.60472437,
        0.65348701,  0.44539031,  0.37723533, -2.41189129,  1.89606216,
        1.27797144, -0.1648901 ,  0.21589155, -0.28559757, -0.46080558,
       -0.51953513, -1.69528363,  0.37571437,  0.58369856, -1.03451246,
        1.66482038,  0.56528328, -0.9990486 ,  0.69375187, -2.05258238,
        0.2361327 ,  0.58765386, -1.73729752,  0.5371405 , -0.352181  ,
        0.28655435, -2.07305138,  0.32962104, -0.28962824,  0.03

In [98]:
g*10000

array([ -3894.91167983,   4282.39294418,   2922.31502865,  14804.09752464,
         8185.05827947,  -1172.92470053, -13527.01241027, -20950.07772542,
        -4395.33038939,   -726.99610304,    647.37248802,   7410.48753581,
        10490.62567929,  12014.09934244, -10425.25879395,  -3458.93986141,
        -6700.98338606,  -4998.40172655,   8859.37550846,  10248.2432233 ,
           71.33969218,  -5686.65050693,  -1942.25452496,   9249.08563491,
       -16464.96104474,   1917.97745559,   3251.88453032,  12327.63138572,
       -12599.24532384,  12885.21155537, -10473.39773088,   1854.08230616,
        -2245.11310464,   3745.77951603,  -2394.77333965,  -9327.70988954,
         4602.10779706,  16876.57323098,  -7276.72455342,   6047.24372017,
         6534.87010976,   4453.90306158,   3772.35326723, -24118.91291744,
        18960.62160796,  12779.71443866,  -1648.90102322,   2158.91554156,
        -2855.97570699,  -4608.05583775,  -5195.35127162, -16952.83629706,
         3757.14372902,  

In [1]:
print("ge")

ge


In [1]:
print("d")

d


------------------------텍스트 -0------------------------------------